### ISSUE TITLE
 无法设置宽度后正常显示

### ISSUE THREAD

**Issue by ysmintor** [dalong982242260/FlowLayout#1]
应该没有在初始化时读取控件的宽度，直接使用了match_parent，希望解决这上问题

**Comment by ysmintor** [comment]
可以按照用户自定义的宽度和高度进入放置子view才符合大多数人的需求，只是按屏幕欧宽度设置不太好！

**Comment by dalong982242260** [comment]
要是自定义了高度  你又设置了文字的大小   高度太小 不够现实完全的时候  应当怎么办呢，加我qq我们一起探讨  982242260

**Comment by yixiaolunhui** [comment]
已修改
